export default {
  LOGIN_SUCCESS: 'LOGIN_API',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  EMAIL_VERIFICATION_SUCCESS: 'EMAIL_VERIFICATION_SUCCESS',
  FORGET_PASSWORD_VERIFICATION_CODE: 'FORGET_PASSWORD_VERIFICATION_CODE',
};
