export default {
  GET_VIBES: 'GET_VIBES',
  GET_VIBE: 'GET_VIBE',
  CREATE_VIBE: 'CREATE_VIBE',
  UPDATE_LIKES: 'UPDATE_LIKES',
  ADD_COMMENT: 'ADD_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  REMOVE_VIBE: 'REMOVE_VIBE',
  DELETE_VIBE: 'DELETE_VIBE',
  CLEAR_VIBE: 'CLEAR_VIBE',
  UPDATE_FAV : 'UPDATE_FAV'
};
